language: java
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- set -e
script:
- "./$CODEBASE/scripts/build"
notifications:
  slack:
    rooms:
    - secure: uRfPABfI45+J6Qapbb5F8FusXPFzHZsOuIN5CtFwzsjZ9Ouvc8aMWVMlaKehhNyrD3YvvYO0KPL/CTWo939VniYQO4ftwghwGWWisKVBmPD640bM/GmzDJ9rMaN/XkDhwUp8R5+YmAeNkcwViHF/v3pI2KQQ0rdc4emUHzHt4cQ3iBI4AzJLqdZnNL1BwpeFmEZakkGAnO7YzJkUKUdsiC7zZdADgnRxzwNZA5mVTmH68Yg1ExCKBNZwg13l4+66L0LuOXB5YTKM0rytK6MVnjPCoMAo2Pt8O5WdvSLirF1p3uUXzWDyyqfqleJGuROg4W4mx5hnCb3pLftfOQXZKpXM6eu4+++Yl5B7bVFaej7KlctqvAgOD2e8Bo5QUM/J1OczagwwkiL9qmUFZ76dJ94ATik/pSCBFmR3IA8hlifuXyL4d4B+n7cEgSYAELKENZhMzmUmiq1WskHuoLKPkJdkiWUhwIO7E54NtjKDc4w5qzqM8FrRS+lA1z+3x17TMB/dn6Y+1/m5Flb/JRs59v9+Ftfx+IThlelFa8zTJcc9KzkCahYWf1MZq6TCawslloi8Fpzqa+WLAvAWYqnFYF3pR/bVU7b3aH5FsJ3ggbNtdrFcwBnVNe79m4iBvw8hZynSINJS3lDCx3hGf9F78fBF7c2j1wmdpUWKcQdqPyU=
